apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
- metallb-subscription.yaml
- metallb-instance.yaml
- hosted-cluster-ingress-ip.yaml
- nmstate-operator.yaml
