variant: openshift
version: 4.14.0
metadata:
  name: disable-eno2
  labels:
    machineconfiguration.openshift.io/role: worker
systemd:
  units:
    - name: disable-eno2.service
      enabled: true
      contents: |
        [Unit]
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/ip link set eno2 down

        [Install]
        WantedBy=default.target
