apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  hosted-cluster-name: vcluster2
resources:
- namespace.yaml
- hostedcluster.yaml
- nodepool.yaml
- sshkey.yaml
- join-clusterset.yaml

configurations:
  - kustomizeconfigs/imagereference.yaml

images:
  - name: ocp-release
    newName: quay.io/openshift-release-dev/ocp-release
    digest: sha256:03cc63c0c48b2416889e9ee53f2efc2c940323c15f08384b439c00de8e66e8aa
