apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-joiner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-joiner
subjects:
- kind: ServiceAccount
  name: cluster-joiner
  namespace: clusters
