apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-joiner
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - patch
  - update
  - list
  - get
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  verbs:
  - create
