apiVersion: batch/v1
kind: Job
metadata:
  name: vcluster1-join-clusterset
  namespace: clusters
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  template:
    spec:
      serviceAccountName: cluster-joiner
      containers:
      - image: cli
        name: vcluster1-patch-managed-cluster
        env:
          - name: CLUSTER_NAME
            value: vcluster1
        command:
          - /bin/sh
          - -c
          - |
            while ! kubectl wait \
                --for condition=ManagedClusterConditionAvailable \
                "managedcluster/${CLUSTER_NAME}"; do
              sleep 1
            done

            kubectl patch "managedcluster/${CLUSTER_NAME}" --type merge --patch '
            {
              "metadata": {
                "labels": {
                  "cluster.open-cluster-management.io/clusterset": "hosted-clusters"
                }
              }
            }
            '
      restartPolicy: Never
