apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  hosted-cluster-name: vcluster1
resources:
- namespace.yaml
- capi-provider-role.yaml
- hostedcluster.yaml
- nodepool.yaml
- infraenv.yaml
- sshkey.yaml
- join-clusterset.yaml
- baremetalhosts
